// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.0
// source: encounter-service/encounter-service.proto

package encounter_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserExperience
type AddXPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Xp int32 `protobuf:"varint,2,opt,name=xp,proto3" json:"xp,omitempty"`
}

func (x *AddXPRequest) Reset() {
	*x = AddXPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddXPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddXPRequest) ProtoMessage() {}

func (x *AddXPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddXPRequest.ProtoReflect.Descriptor instead.
func (*AddXPRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddXPRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddXPRequest) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

type GetXPByUserIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetXPByUserIdRequest) Reset() {
	*x = GetXPByUserIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetXPByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXPByUserIdRequest) ProtoMessage() {}

func (x *GetXPByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXPByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetXPByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetXPByUserIdRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StatusCodeResponseEncounter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *StatusCodeResponseEncounter) Reset() {
	*x = StatusCodeResponseEncounter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusCodeResponseEncounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCodeResponseEncounter) ProtoMessage() {}

func (x *StatusCodeResponseEncounter) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCodeResponseEncounter.ProtoReflect.Descriptor instead.
func (*StatusCodeResponseEncounter) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusCodeResponseEncounter) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type UserExperience struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ExperiencePoints int32 `protobuf:"varint,3,opt,name=experiencePoints,proto3" json:"experiencePoints,omitempty"`
	Level            int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *UserExperience) Reset() {
	*x = UserExperience{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_encounter_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserExperience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExperience) ProtoMessage() {}

func (x *UserExperience) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_encounter_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExperience.ProtoReflect.Descriptor instead.
func (*UserExperience) Descriptor() ([]byte, []int) {
	return file_encounter_service_encounter_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserExperience) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserExperience) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserExperience) GetExperiencePoints() int32 {
	if x != nil {
		return x.ExperiencePoints
	}
	return 0
}

func (x *UserExperience) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_encounter_service_encounter_service_proto protoreflect.FileDescriptor

var file_encounter_service_encounter_service_proto_rawDesc = []byte{
	0x0a, 0x29, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x0c, 0x41, 0x64,
	0x64, 0x58, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x78, 0x70, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x58, 0x50, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x1b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x7a, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x99, 0x03, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x1c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x3a, 0x01, 0x2a, 0x22,
	0x1b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x05,
	0x41, 0x64, 0x64, 0x58, 0x50, 0x12, 0x0d, 0x2e, 0x41, 0x64, 0x64, 0x58, 0x50, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72,
	0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x3a, 0x01, 0x2a,
	0x1a, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x6c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x58, 0x50, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x58, 0x50, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x33, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x2d, 0x12, 0x2b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73,
	0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x78, 0x70, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x7d,
	0x12, 0x60, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22,
	0x2a, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x69, 0x73, 0x74, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_encounter_service_encounter_service_proto_rawDescOnce sync.Once
	file_encounter_service_encounter_service_proto_rawDescData = file_encounter_service_encounter_service_proto_rawDesc
)

func file_encounter_service_encounter_service_proto_rawDescGZIP() []byte {
	file_encounter_service_encounter_service_proto_rawDescOnce.Do(func() {
		file_encounter_service_encounter_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounter_service_encounter_service_proto_rawDescData)
	})
	return file_encounter_service_encounter_service_proto_rawDescData
}

var file_encounter_service_encounter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_encounter_service_encounter_service_proto_goTypes = []interface{}{
	(*AddXPRequest)(nil),                // 0: AddXPRequest
	(*GetXPByUserIdRequest)(nil),        // 1: GetXPByUserIdRequest
	(*DeleteRequest)(nil),               // 2: DeleteRequest
	(*StatusCodeResponseEncounter)(nil), // 3: StatusCodeResponseEncounter
	(*UserExperience)(nil),              // 4: UserExperience
}
var file_encounter_service_encounter_service_proto_depIdxs = []int32{
	4, // 0: EncounterService.Create:input_type -> UserExperience
	0, // 1: EncounterService.AddXP:input_type -> AddXPRequest
	1, // 2: EncounterService.GetXPByUserId:input_type -> GetXPByUserIdRequest
	2, // 3: EncounterService.Delete:input_type -> DeleteRequest
	3, // 4: EncounterService.Create:output_type -> StatusCodeResponseEncounter
	4, // 5: EncounterService.AddXP:output_type -> UserExperience
	4, // 6: EncounterService.GetXPByUserId:output_type -> UserExperience
	3, // 7: EncounterService.Delete:output_type -> StatusCodeResponseEncounter
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_encounter_service_encounter_service_proto_init() }
func file_encounter_service_encounter_service_proto_init() {
	if File_encounter_service_encounter_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounter_service_encounter_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddXPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetXPByUserIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusCodeResponseEncounter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_encounter_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserExperience); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounter_service_encounter_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encounter_service_encounter_service_proto_goTypes,
		DependencyIndexes: file_encounter_service_encounter_service_proto_depIdxs,
		MessageInfos:      file_encounter_service_encounter_service_proto_msgTypes,
	}.Build()
	File_encounter_service_encounter_service_proto = out.File
	file_encounter_service_encounter_service_proto_rawDesc = nil
	file_encounter_service_encounter_service_proto_goTypes = nil
	file_encounter_service_encounter_service_proto_depIdxs = nil
}
