version: "3.9"

services:

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    hostname: api-gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    environment: 
      TOUR_SERVICE_ADDRESS: tour-service:8000
      GATEWAY_ADDRESS: "8000"
    depends_on:
      - tour-service
    networks:
      - network
    ports:
      - "8000:8000"
      - "8090:8090"


  tour-service:
    image: tour-service
    container_name: tour-service
    hostname: tour-service
    build:
      context: ./golang-be/Tours/
    restart: on-failure
    expose:
      - "8000:8000"
    networks:
      - network
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://root:jemta@mongo:27017/
      TOUR_ADDRESS: "8000"

  mongo:
    image: mongo
    restart: always
    networks: 
     - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jemta
      MONGO_INITDB_DATABASE: tour
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: jemta
      ME_CONFIG_MONGODB_URL: mongodb://root:jemta@mongo:27017/
      ME_CONFIG_BASICAUTH: false
     
networks:
  network:
    driver: bridge

