{
 "title": "metrics-host",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(instance:node_cpu_usage:per_core)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Core",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_usage:per_core",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "instance:node_memory_usage_bytes:total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write Usage (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "instance:node_disk_write_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Read Usage (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "instance:node_disk_read_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Transmit (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "instance:node_network_transmit_mb",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_mb",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}