{
 "title": "metrics-container",
 "time": { "from": "2024-05-31T00:39:08.087Z", "to": "2024-05-31T12:39:08.087Z" },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:container_cpu_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "instance:container_memory_usage_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "instance:container_network_transmit_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "instance:container_network_receive_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container filesystem disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "instance:container_fs_usage_bytes:sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}